// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POC.Database;

#nullable disable

namespace POC.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20230514104558_AddOrdersTableToDB")]
    partial class AddOrdersTableToDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("POC.Models.Orders", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("OrderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            DisplayOrder = 1,
                            OrderName = "Iphone 13 Mobile"
                        },
                        new
                        {
                            OrderId = 2,
                            DisplayOrder = 2,
                            OrderName = "Iphone 13 Charger"
                        },
                        new
                        {
                            OrderId = 3,
                            DisplayOrder = 3,
                            OrderName = "Iphone 13 Earphone"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
